### ISSUE TITLE
linux/ppc64 - cannot use dynamic imports with -d flag

### ISSUE THREAD

**Issue by andrewkroh** [elastic/golang-crossbuild#1]
Dynamic linking using linux/ppc64 fails with:

`/usr/local/go/pkg/tool/linux_amd64/link: $WORK/b088/_pkg_.a(_go_.o): cannot use dynamic imports with -d flag`

I don't think there's much we can do here.

https://github.com/golang/go/issues/13192

**Comment by kuisathaverat** [comment]
@andrewkroh Is this still valid? Do you have an example?

**Comment by andrewkroh** [comment]
IIRC I think this was while building beats for `linux/ppc64` but no one targets that OS in my experience so this isn't a problem in practice.
