### ISSUE TITLE
darwin-arm64 tag

### ISSUE THREAD

**Issue by Sikerdebaard** [elastic/golang-crossbuild#112]
Hi,

Thank you so much for making these images. These images have saved me a lot of time. Cross compilation of GoLang is really fiddly to me.

In the commit history there's talk about supporting darwin-arm64. However, I can't seem to pull the image for this from the docker repository. Furthermore in de README.md it is suggested that 1.16.4-darwin can build for the darwin-386 platform but this does not seem to work. Are these two platforms not supported?

**Comment by Sikerdebaard** [comment]
Found out about the 1.16.4-darwin-arm64-debian10 image. Doh.

However the arm64 and the amd64 build seem to get stuck on the following error.

```bash
# command-line-arguments
/usr/local/go/pkg/tool/linux_amd64/link: running o64-clang failed: exit status 1
Undefined symbols for architecture x86_64:
  "_clock_gettime", referenced from:
      _runtime.walltime_trampoline in go.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Makefile:10: recipe for target 'build' failed
make: *** [build] Error 1
Error: failed building for darwin/amd64: exit status 2
failed building for darwin/amd64: exit status 2
make: *** [Makefile:18: build] Error 1
```

Looks like a similar issue to #93 except this time on arm64.

**Comment by kuisathaverat** [comment]
I am not sure what could be your issue, we tested that we can generate binaries on Docker container build. Also, I have tested that I can compile a hello world for darwin/arm64

```shell
git clone https://github.com/go-training/helloworld
cd helloworld
docker run --rm \
  -v $(pwd):/go/src/github.com/go-training/helloworld \
  -w /go/src/github.com/go-training/helloworld \
  docker.elastic.co/beats-dev/golang-crossbuild:1.16.6-darwin-arm64-debian10 \
    --build-cmd "go mod init;go mod tidy;go build" -p "darwin/arm64"
```
