### ISSUE TITLE
armv6 hf pi zero

### ISSUE THREAD

**Issue by Sikerdebaard** [elastic/golang-crossbuild#113]
Hi,

Is there an image to cross compile to armv6 with armhf? Currently only armv7 through the 1.16.4-armhf image seems to be supported according to the documentation.

The Raspberry Pi Model A, B, B+, the Compute Module, and the Raspberry Pi Zero all run on this architecture.

https://www.raspberrypi.org/documentation/hardware/raspberrypi/bcm2835/README.md

**Comment by kuisathaverat** [comment]
I am afraid not, the `armhf` image support only `armv7` (https://github.com/elastic/golang-crossbuild/blob/master/go1.16/armhf/rootfs/compilers.yaml), the `armel` is the one that has support for `armv5` and `armv6`

However, I have tested to compile for armv6 and run a binary in one of my Raspberry pi and it works

```shell
pi@raspberrypi:~ $ cat /proc/cpuinfo 
processor	: 0
model name	: ARMv6-compatible processor rev 7 (v6l)
BogoMIPS	: 697.95
Features	: half thumb fastmult vfp edsp java tls 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xb76
CPU revision	: 7

Hardware	: BCM2835
Revision	: 100000e
Serial		: FOOOOOOOOOOOO
Model		: Raspberry Pi Model B Rev 2
```

```shell
git clone https://github.com/go-training/helloworld
cd helloworld
docker run --rm -v $(pwd):/go/src/github.com/go-training/helloworld -w /go/src/github.com/go-training/helloworld docker.elastic.co/beats-dev/golang-crossbuild:1.16.6-armel-debian10 --build-cmd "go mod init;go mod tidy;go build" -p "linux/armv6"
```
