### ISSUE TITLE
A few unavailable build tags on docker.elastic.co: Where can we see what's available? 

### ISSUE THREAD

**Issue by jdrews** [elastic/golang-crossbuild#121]
I've noticed that not every [build tag listed on the README.md](https://github.com/elastic/golang-crossbuild#build-tags) is available on docker.elastic.co. For example `1.16.4-debian10` and `1.16.4-debian8` return the following error when doing a `docker pull`. 
`docker: Error response from daemon: manifest for docker.elastic.co/beats-dev/golang-crossbuild:1.16.4-debian10 not found: manifest unknown: manifest unknown.`

Usually on docker registries you can check via `https://docker.elastic.co/v2/beats-dev/golang-crossbuild/tags/list` but that returns "UNAUTHORIZED". Please advise. Thanks!

**Comment by jdrews** [comment]
Hmm I finally got the `Makefile` working so I could build locally. I'm noticing that the debian8 images are called `1.16.4-main-debian8`. I wonder if that's the problem and we just need to update the README.md? 

Regardless, it'd be swell if we could `tags/list` the available images from `docker.elastic.co`.

**Comment by jdrews** [comment]
Yep confirmed-- I can pull down `1.16.4-main-debian10` and `1.16.4-main-debian8` but not `1.16.4-debian10` and `1.16.4-debian8` as listed on the [build tags section of the README.md](https://github.com/elastic/golang-crossbuild#build-tags). Recommend updating the README.md

**Comment by v1v** [comment]
Thanks @jdrews for raising this issue.

As you noticed this particular docker tags have been evolving among the time. The docker registry is limited in what entrypoint can be accessed. We will update the tags section to add more clarity.

Thanks again

**Comment by jdrews** [comment]
Looks great! Thanks!
