### ISSUE TITLE
darwin/arm64

### ISSUE THREAD

**Issue by gsmachado** [elastic/golang-crossbuild#150]
Hello,

This repo is AWESOME! Some time ago I was building something similar, but now I'm using this one. Congrats.

So, any chance to include `darwin/arm64` in the next release? Like, generate an image tag like:

`docker.elastic.co/beats-dev/golang-crossbuild:1.17.6-darwin-arm64` or something similar..

If that's challenging, can you point me where should I look to get into it, do it by myself, and maybe submit a PR?

Thanks in advance.

**Comment by gsmachado** [comment]
OH, just found out this issue: https://github.com/elastic/golang-crossbuild/issues/112

I can just use `docker.elastic.co/beats-dev/golang-crossbuild:1.17.6-darwin-arm64-debian10`. Great!

Just one thing: please include this image tag in [your release notes](https://github.com/elastic/golang-crossbuild/releases/tag/1.17.6)! It makes it easier to find.

**Comment by missinglink** [comment]
Thanks @gsmachado, the `1.17.6-darwin-arm64-debian10` image also allowed me to build for MacOS with CGO enabled.

Out of curiosity, how did you find this image!? I wanted to check if there was potentially undocumented support for building for the M1/M2 chips with ARM
