### ISSUE TITLE
windows32 builds did not work until I set up `CGO_CFLAGS="-D_WIN32_WINNT=0x0600"`

### ISSUE THREAD

**Issue by igor-hnizdo** [elastic/golang-crossbuild#231]
I had weird issues with builds for windows32; I kept getting

```
undefined reference to `SleepConditionVariableCS'
```

and such.

When I used

```
CGO_CFLAGS="-D_WIN32_WINNT=0x0600"
```

everything started to work. As that seems to be Windows version Vista, where that particular API has been introduced in kernel32.

I copied the line from here

https://github.com/karalabe/xgo/blob/c5ccff8648a77686d274c1984e1cd6319736f5cb/docker/base/build.sh#L442

It should be at least documented somewhere. Or maybe, even pre-filled (I don't think people will build binaries for pre-Vista Windows, but who knows)

**Comment by kuisathaverat** [comment]
We have dropped support to win32, but yep we should put it in the README, and stop releasing i386 Docker images

**Comment by v1v** [comment]
https://github.com/elastic/golang-crossbuild/pull/304 has been merged, so docs are now reflecting that windows/i386 is not something supported even though if docker images are available.

I'll close this issue now
