### ISSUE TITLE
Automate publishing golang-crossbuild images for new Go versions

### ISSUE THREAD

**Issue by andrewkroh** [elastic/golang-crossbuild#25]
We should setup Jenkins CI for the repo to test pull requests automatically.

Also we want to automate publishing new images when changes are made.

**Comment by v1v** [comment]
> We should setup Jenkins CI for the repo to test pull requests automatically.

PRs will build and push changes to the staging docker registry.

> Also we want to automate publishing new images when changes are made.

Commits to master will automatically build and push docker images to the production docker registry.

https://github.com/elastic/golang-crossbuild/pull/54 implemented the above features and it has been merged.  https://github.com/elastic/golang-crossbuild/pull/56 has been created to update the docs references.

Is this issue ready to be closed?

**Comment by mikemadden42** [comment]
@v1v I think this issue can be closed.  @andrewkroh what do you think?

**Comment by v1v** [comment]
For the record, the very first automated release from the master branch just happened -> https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fgolang-crossbuild-mbp/detail/master/3/pipeline/145
