### ISSUE TITLE
Some Docker images are not available?

### ISSUE THREAD

**Issue by xeraa** [elastic/golang-crossbuild#295]
Coming from a [Discuss question](https://discuss.elastic.co/t/https-docker-auth-elastic-co-not-working/334665) I can pull some images like `docker pull docker.elastic.co/beats-dev/golang-crossbuild:1.17.1-ppc` but not others like `docker pull docker.elastic.co/beats-dev/golang-crossbuild:1.19.9-ppc`, which is listed on https://github.com/elastic/golang-crossbuild/releases.

Though on https://container-library.elastic.co/r/beats-dev/golang-crossbuild?limit=50&offset=150&show_snapshots=false I can see that `docker pull docker.elastic.co/beats-dev/golang-crossbuild:1.19.9-ppc-debian11` is available.
So a small doc fix for the release notes? Or should we add an alias for the "imageless" version without `-debian11`?

**Comment by andrewkroh** [comment]
On a related not, Beats can be build for linux/ppc64le with this command. It fails because it is looking for the debian10 variant.

`PLATFORMS="+all linux/ppc64le" mage -v package`

`Unable to find image 'docker.elastic.co/beats-dev/golang-crossbuild:1.19.9-ppc-debian10' locally`

**Comment by v1v** [comment]
```bash
$ curl -s https://beats-ci.elastic.co/job/golang-crossbuild/job/golang-crossbuild-mbp/job/1.19/lastSuccessfulBuild/consoleText | grep 'Z] >> Pushing '  | sed 's#.*Z\] >> Pushing ##g' | cut -d' ' -f1 | sort | uniq
```

produced:

```
docker.elastic.co/beats-dev/golang-crossbuild:1.19.10-armel
docker.elastic.co/beats-dev/golang-crossbuild:1.19.10-armel-debian11
docker.elastic.co/beats-dev/golang-crossbuild:1.19.10-armel-debian9
docker.elastic.co/beats-dev/golang-crossbuild:1.19.10-armhf
docker.elastic.co/beats-dev/golang-crossbuild:1.19.10-armhf-debian10
docker.elastic.co/beats-dev/golang-crossbuild:1.19.10-armhf-debian11
docker.elastic.co/beats-dev/golang-crossbuild:1.19.10-armhf-debian9
docker.elastic.co/beats-dev/golang-crossbuild:1.19.10-base-arm-debian9
docker.elastic.co/beats-dev/golang-crossbuild:1.19.10-base-debian7
docker.elastic.co/beats-dev/golang-crossbuild:1.19.10-base-debian8
docker.elastic.co/beats-dev/golang-crossbuild:1.19.10-darwin
docker.elastic.co/beats-dev/golang-crossbuild:1.19.10-darwin-debian8
docker.elastic.co/beats-dev/golang-crossbuild:1.19.10-darwin-debian9
docker.elastic.co/beats-dev/golang-crossbuild:1.19.10-main
docker.elastic.co/beats-dev/golang-crossbuild:1.19.10-main-debian10
docker.elastic.co/beats-dev/golang-crossbuild:1.19.10-main-debian11
docker.elastic.co/beats-dev/golang-crossbuild:1.19.10-main-debian7
docker.elastic.co/beats-dev/golang-crossbuild:1.19.10-main-debian8
docker.elastic.co/beats-dev/golang-crossbuild:1.19.10-main-debian9
docker.elastic.co/beats-dev/golang-crossbuild:1.19.10-mips-debian11
docker.elastic.co/beats-dev/golang-crossbuild:1.19.10-ppc-debian11
docker.elastic.co/beats-dev/golang-crossbuild:1.19.10-s390x-debian11
```

As far as I see `docker.elastic.co/beats-dev/golang-crossbuild:1.19.10-armhf` and `docker.elastic.co/beats-dev/golang-crossbuild:1.19.10-armel` are aliases for `Debian 9`.  See https://github.com/elastic/golang-crossbuild/blob/main/go/Makefile and https://github.com/elastic/golang-crossbuild/blob/main/go/Makefile.debian9#L1

> Or should we add an alias for the "imageless" version without -debian11?

https://github.com/elastic/golang-crossbuild/pull/175 was the one removing the support for `Debian 9`, aka, the one without the suffix `-debian9`. Unfortunately, the suffix `-debian11` is included automatically as per designed in https://github.com/elastic/golang-crossbuild/blob/main/go/Makefile.debian11#L3.


> So a small doc fix for the release notes?

I think that's the quickest approach IMO

**Comment by v1v** [comment]
https://github.com/elastic/golang-crossbuild/pull/302 is the fix for the README.me and the release notes automation.

In addition I fixed the references for all the docker images in all the releases for `1.20` and `1.19`.
