### ISSUE TITLE
Switch from Debian 7 to CentOS 6

### ISSUE THREAD

**Issue by mikemadden42** [elastic/golang-crossbuild#49]
- Switch from Debian 7 since the apt repos are no longer signed; the keys have expired.
- Build a Centos 6 based builder image with all of the required deps included (systemd, libpcap, librpm, etc).
- Remove the apt commands from mage files.
- Keep the resulting image updated consistently.
- May need to pull in the source for systemd since centos 6 does not support it.

**Comment by andrewkroh** [comment]
Relates: https://github.com/elastic/beats/issues/11750

**Comment by mikemadden42** [comment]
I’m trying to build systemd for centos 6.  I’m fighting with dependencies for meson/systemd.  The build process is a little complex for something like Ubuntu 18.04, but it’s much more painful for something old like centos 6 which does not natively support systemd.

I’m getting stuck in the systemd build for centos 6 at this point.

```
The local user with the configured user name "nobody" of the nobody user does not have UID 65534 (it has 99).
Your build will result in an user table setup that is incompatible with the local system.
meson.build:756: WARNING:
The local group with the configured group name "nobody" of the nobody group does not have UID 65534 (it has 99).
Your build will result in an group table setup that is incompatible with the local system.
Program tools/choose-default-locale.sh found: YES (/root/systemd-245/tools/choose-default-locale.sh)
Dependency threads found: YES
Library rt found: YES
Library m found: YES
Library dl found: YES
Library crypt found: YES
Found pkg-config: /usr/bin/pkg-config (0.23)
Found CMake: NO
Dependency libcap found: NO (tried pkgconfig and cmake)
Library cap found: YES
Dependency mount found: NO (tried pkgconfig)
meson.build:870:0: ERROR:  Dependency "mount" not found, tried pkgconfig
14:37
```

On Debian/Ubuntu, I had to install libmount-dev, but I do not see anything related to libmount on centos 6.

I wrote a small script to help automate the install of the `systemd` package.  It works well for Ubuntu 18.04, but it has the issues I mentioned above on CentOS 6.

```
#!/bin/sh

# https://github.com/mesonbuild/meson/releases
#MESON_VER=0.54.2
MESON_VER=0.49.2
# https://github.com/systemd/systemd/releases
SYSTEMD_VER=245

# Use these commands to install dependencies on Ubuntu 18.04
#sudo apt install -y gperf libcap-dev libmount-dev m4

# Use these commands to install dependencies on CentOS 6
yum install -y centos-release-scl epel-release
yum install -y gcc gperf libcap-devel m4 ninja-build python34 rh-python35-python util-linux-ng wget
. /opt/rh/rh-python35/enable
cat >/usr/bin/realpath
#!/bin/sh
readlink -f -- "$@"
chmod 755 /usr/bin/realpath

wget -c https://github.com/mesonbuild/meson/releases/download/${MESON_VER}/meson-${MESON_VER}.tar.gz
tar xfz meson-${MESON_VER}.tar.gz
cd meson-${MESON_VER}
ln -s meson.py meson
export PATH=${PWD}:${PATH}

cd
wget -c https://github.com/systemd/systemd/archive/v${SYSTEMD_VER}.tar.gz
tar xfz v${SYSTEMD_VER}.tar.gz
cd systemd-${SYSTEMD_VER}
./configure
make
export DESTDIR=/tmp/systemd-${SYSTEMD_VER}
mkdir -p ${DESTDIR}
make install
echo "systemd installed in ${DESTDIR}"
```

**Comment by mikemadden42** [comment]
There were some suggestion to resolve the issues with `libmount`.

> libmount is inside the util-linux https://github.com/karelzak/util-linux/tree/master/libmount I did find packages fro centOS 6, for other versions you have :man-shrugging: so I have search for util-linux and libmount is in it https://centos.pkgs.org/6/centos-x86_64/util-linux-ng-2.17.2-12.28.el6_9.2.x86_64.rpm.html but there is no devel package so I guess you can copy the files from the sources in the same version, here you have the list of files you need https://cbs.centos.org/koji/rpminfo?rpmID=81562 but it is normal centOS 6 was released on 2011-07-10

 I did install the package, but as I suspected it does not include any header files.

```
[root@dc67996c7e23 systemd-245]# rpm -q util-linux-ng
util-linux-ng-2.17.2-12.28.el6_9.2.x86_64
meson.build:870:0: ERROR:  Dependency "mount" not found, tried pkgconfig

[root@dc67996c7e23 systemd-245]# which mount
/bin/mount

[root@dc67996c7e23 systemd-245]# rpm -qf /bin/mount
util-linux-ng-2.17.2-12.28.el6_9.2.x86_64
20:49
```

I’m not seeing anything that provides libmount.h.
```
[root@dc67996c7e23 systemd-245]# yum provides "*/libmount.h"
Loaded plugins: fastestmirror, ovl
Loading mirror speeds from cached hostfile
 * base: centos.mirror.lstn.net
 * centos-sclo-rh: mirror.sesp.northwestern.edu
 * centos-sclo-sclo: mirror.steadfastnet.com
 * epel: mirror.team-cymru.com
 * extras: ftpmirror.your.org
 * updates: centos.mirror.lstn.net
No Matches found
```

On a Debian/Ubuntu system, you have these files in the package, but I’m not seeing an equivalent on centos 6.
```
michael_madden@beats-madden-ubuntu-18-04:~$ dpkg -L libmount-dev
/.
/usr
/usr/include
/usr/include/libmount
/usr/include/libmount/libmount.h
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/libmount.a
/usr/lib/x86_64-linux-gnu/pkgconfig
/usr/lib/x86_64-linux-gnu/pkgconfig/mount.pc
/usr/share
/usr/share/doc
/usr/share/doc/libmount-dev
/usr/share/doc/libmount-dev/copyright
/usr/lib/x86_64-linux-gnu/libmount.so
/usr/share/doc/libmount-dev/changelog.Debian.gz
```

**Comment by mikemadden42** [comment]
I wonder if switching to CentOS 6 from Debian 7 makes sense.  CentOS 6 is EOL at the end of this year.  It was released in November 2010, and it’s EOL in November 2020.  It feels like it's going to take a lot of effort to get systemd working on CentOS 6.  I'm not sure if it's technically possible without upgrading a lot of core components.

https://access.redhat.com/support/policy/updates/errata#Life_Cycle_Dates

**Comment by mikemadden42** [comment]
CentOS 7 natively supports systemd and provides `systemd-devel` so we could build journalbeat.

There's still the question about glibc compatability.  If we move to something like CentOS 7 will we break beats on older distros that we still support?

https://github.com/elastic/beats/issues/11750#issuecomment-623765019

It looks like if we switched to CentOS 7 for golang-crossbuild, we would break beats on centos 6, debian 7, and ubuntu 12.04.

**Comment by andrewkroh** [comment]
What would the impact be of moving only journalbeat to CentOS 7? Journalbeat is using the Debian 8 image instead of the Debian 7.

**Comment by kuisathaverat** [comment]
<img width="992" alt="Screenshot 2020-06-02 at 09 38 56" src="https://user-images.githubusercontent.com/5400788/83493338-ecac3a00-a4b4-11ea-9495-62ffc4729ac3.png">

**Comment by kuisathaverat** [comment]
With Ubuntu LTS we are in the same place we have to use 14.04

https://ubuntu.com/about/release-cycle

<img width="946" alt="Screenshot 2020-06-02 at 09 47 16" src="https://user-images.githubusercontent.com/5400788/83494110-1154e180-a4b6-11ea-9fd3-0eaeccd8d435.png">

**Comment by kuisathaverat** [comment]
Do we know the kind of issues we will have if we use Debian 9/10? Are those issues related to library versions?

**Comment by urso** [comment]
CentOS 6 was chosen also because it has an older glibc version. Compiling Beats by default with a newer libc version can potentially affect our binaries not running on older distributions.

**Comment by kuisathaverat** [comment]
Why do not use a modern distribution and compile with an old libc?
https://www.tldp.org/HOWTO/Glibc2-HOWTO-6.html

**Comment by andresrc** [comment]
We have several issues here:
* We need to support the platforms supported by endpoint security because of the agent.
* We can make changes for 8.0, but we would need to coordinate beats / agent / endpoint.
* We should avoid big changes in 7.x to reduce the risk of unexpected consequences.

My understanding is that the debian 7 repos are not signed, but given that it is EOL'd: do we expect upgrades? Can we make a debian 7 image which what we have now and avoid upgrading it during the build process?

**Comment by kuisathaverat** [comment]
>My understanding is that the debian 7 repos are not signed, but given that it is EOL'd: do we expect upgrades? Can we make a debian 7 image which what we have now and avoid upgrading it during the build process?

no after 2020-06-30, there is not extended support yet

**Comment by andresrc** [comment]
what I mean is whether we are able create our own debian 7-based base image with all we need for the builds and just leave it in some internal repository just for them, even if the support has ended. For 8.x we would just move to CentOS 7.

**Comment by mikemadden42** [comment]
@andresrc I like your idea of creating an image based on Debian 7 that contains all the needed build components for beats.  We could use that image until we could make a switch to an image based on CentOS 7.

CentOS 7 still has ~ 4 years of support.
https://access.redhat.com/support/policy/updates/errata#Life_Cycle_Dates
