### ISSUE TITLE
Add libpcap / winpcap to image

### ISSUE THREAD

**Issue by andrewkroh** [elastic/golang-crossbuild#63]
Packetbeat builds libpcap from source every time packaging runs. It downloads 1.8.1 and builds a static library. It would be beneficial to do this once when the images are built rather then anytime packetbeat is built. This is where Packetbeat run the build commands:

https://github.com/elastic/beats/blob/941709b4b9455a435b4afba9b2704360be7e75bd/packetbeat/magefile.go#L254-L285

And on Windows it installs WinPCAP so that it can link against it (dynamically). So these commands could also be added to the image.

https://github.com/elastic/beats/blob/941709b4b9455a435b4afba9b2704360be7e75bd/packetbeat/magefile.go#L377-L409

**Comment by kuisathaverat** [comment]
for Linux it is possible and easy, for windows the `wpcap.def` depends on the beats, I am not sure is not possible to generate a def file for all the beats.

**Comment by andrewkroh** [comment]
I think it only depends on beats in that elastic/beats has a copy of the DLL needed to create the winpcap static library. https://github.com/elastic/beats/issues/1259#issuecomment-204085873
