### ISSUE TITLE
Package conflicts in ARM images

### ISSUE THREAD

**Issue by jsoriano** [elastic/golang-crossbuild#67]
Images for ARM have [some packages preinstalled](https://github.com/elastic/golang-crossbuild/blob/7fe9c7c0bcde40f473473271f8b807557d74c683/go1.14/arm/Dockerfile.tmpl#L13). The crossbuild packages are installed for several variants of arm, but some development packages are installed only for `arm64`.
When using the image, installation of some of these development packages for other arm variants fail due to conflict with installed packages (see https://github.com/elastic/beats/pull/21239, where libicu-dev needs to be explicitly installed to be able to install librpm-dev).
We should find a solution for these conflicts. So the required packages are preinstalled and build scripts don't need to install additional packages, what will fail if the base distribution is discontinued.
If packages cannot be installed in the same image, maybe we need to provide a different image for each arm variant.

**Comment by kuisathaverat** [comment]
because of that, we have to make https://github.com/elastic/golang-crossbuild/pull/62

**Comment by kuisathaverat** [comment]
now there are one image by architecture:
* docker.elastic.co/beats-dev/golang-crossbuild:1.16.4-arm - arm64
* docker.elastic.co/beats-dev/golang-crossbuild:1.16.4-armel - armv5 ,armv6
* docker.elastic.co/beats-dev/golang-crossbuild:1.16.4-armhf - armv7
* docker.elastic.co/beats-dev/golang-crossbuild:1.16.4-mips - armv7 - mips64,mips64le
* docker.elastic.co/beats-dev/golang-crossbuild:1.16.4-mips32 - armv7 - mips,mipsle
