### ISSUE TITLE
Python3 missing/broken

### ISSUE THREAD

**Issue by alucardtheunnamedlord** [elastic/golang-crossbuild#92]
Tried the following:

Running Win 10 Pro (OS Build 19041.867) with Docker Desktop v20.10.6

Pulled latest images

docker pull docker.elastic.co/beats-dev/golang-crossbuild:1.16.4-ppc-debian10
docker pull docker.elastic.co/beats-dev/golang-crossbuild:1.16.4-main

PPC64LE:

docker run -it --rm -v  C:\Docker\github.com:/go/src/github.com -w /go/src/github.com/elastic/beats -e CGO_ENABLED=1 docker.elastic.co/beats-dev/golang-crossbuild:1.16.4-ppc-debian10 --build-cmd "make release" -p "linux/ppc64le"

results in :
go mod download
go list -m -json all | go run go.elastic.co/go-licence-detector \
        -includeIndirect \
        -rules dev-tools/notice/rules.json \
        -overrides dev-tools/notice/overrides.json \
        -noticeTemplate dev-tools/notice/NOTICE.txt.tmpl \
        -noticeOut NOTICE.txt \
        -depsOut ""
make[1]: Entering directory '/go/src/github.com/elastic/beats/libbeat'
bash: python3: command not found
make[1]: *** [scripts/Makefile:272: python-env] Error 127
make[1]: Leaving directory '/go/src/github.com/elastic/beats/libbeat'
make: *** [Makefile:81: update] Error 1
Error: failed building for linux/ppc64le: exit status 2
failed building for linux/ppc64le: exit status 2

AMD64:

docker run -it --rm -v C:\Docker\github.com:/go/src/github.com -w /go/src/github.com/elastic/beats -e CGO_ENABLED=1 docker.elastic.co/beats-dev/golang-crossbuild:1.16.4-main --build-cmd "make release" -p "linux/amd64"

o list -m -json all | go run go.elastic.co/go-licence-detector \
        -includeIndirect \
        -rules dev-tools/notice/rules.json \
        -overrides dev-tools/notice/overrides.json \
        -noticeTemplate dev-tools/notice/NOTICE.txt.tmpl \
        -noticeOut NOTICE.txt \
        -depsOut ""
make[1]: Entering directory '/go/src/github.com/elastic/beats/libbeat'
bash: python3: command not found
scripts/Makefile:272: recipe for target 'python-env' failed
make[1]: *** [python-env] Error 127
make[1]: Leaving directory '/go/src/github.com/elastic/beats/libbeat'
Makefile:81: recipe for target 'update' failed
make: *** [update] Error 1
Error: failed building for linux/amd64: exit status 2
failed building for linux/amd64: exit status 2

Looks like Python3x is missing from the base image

**Comment by kuisathaverat** [comment]
I do not expect that Beats compile with Go 1.16 yet, the supported version 1.15.12 is (see https://github.com/elastic/beats/blob/master/.go-version) but I will take a look at the Python version installed

**Comment by kuisathaverat** [comment]
BTW I have checked old images and Python was never installed on the Docker images, so it is not possible to compile Beats using beats targets with any image published until now, however, I see the benefit to add python to the latest Debian 10 Docker images to make possible to compile Beats.
